### ISSUE TITLE
StoreImageJob missing full namespace

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight_sidecar_images#16]
https://github.com/geoblacklight/geoblacklight_sidecar_images/blob/master/lib/tasks/geoblacklight_sidecar_images_tasks.rake#L23

Should be GeoblacklightSidecarImages::StoreImageJob

**Comment by eliotjordan** [comment]
Looks like develop needs to be merged into master and a new release cut.

https://github.com/geoblacklight/geoblacklight_sidecar_images/blob/develop/lib/tasks/geoblacklight_sidecar_images_tasks.rake#L23

**Comment by ewlarson** [comment]
Closing. Fixed in [0.6.4](https://github.com/geoblacklight/geoblacklight_sidecar_images/releases/tag/0.6.4)
