### ISSUE TITLE
Can't run specs

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight_sidecar_images#18]
engine_cart fails to create a test app. Conflicts include:

- sass-rails
- sprockets
- something to do with safe_load:

```
/Users/eliotj/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/psych.rb:328:in `safe_load': unknown keywords: whitelist_classes, whitelist_symbols (ArgumentError)
```

**Comment by ewlarson** [comment]
Fixed with bf62bd46d1cdfd7c04bb75c594418c7fb793b185 - added a development dependency to keep sprockets 4 from coming along.

TravisCI is [green](https://travis-ci.org/geoblacklight/geoblacklight_sidecar_images/builds/658814148) again
